### ISSUE TITLE
Take this project offline until you've made it truly opt-in. 

### ISSUE THREAD

**Issue by ThatOneCalculator** [tedivm/fedimapper#8]
Since it's clear you don't want to respond to #7's discussion, I feel this project should be taken offline for the safety of the Fediverse until you can give everyone a far less controversial and harmful system. (i.e. making it EXPLICITLY opt in)

**Comment by tedivm** [comment]
I've been responding, I just have also been interviewing for jobs. I'm closing this as a duplicate.
